[connections.supabase]
SUPABASE_URL = "https://feymqznbaxqtlmvewzvn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZleW1xem5iYXhxdGxtdmV3enZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTAyMDA4ODMsImV4cCI6MjAyNTc3Njg4M30.e1khNhB4dT8BT5XfitWWV4_96vk5GAIBk9xYarX6ueM"